"use client";
import { useEffect, useRef, useState } from "react";
import styles from "./Pricing.module.css";
const completedScenes = new Set<string>();
const data={
"Виниловая плёнка":[["Полная оклейка автомобиля","160 000"],["Оклейка крыши","19 000"],["Капот","19 000"],["Передний бампер","28 000"],["Задний бампер","25 000"],["Переднее крыло","13 000"],["Заднее крыло","23 000"],["Дверь (одна)","13 000"],["Пороги (пара)","18 000"],["Зеркала (пара)","12 000"],["Спойлер","10 000"],["Молдинги (комплект)","8 000"],["Рейлинги (пара)","23 000"]],
"Защитная плёнка":[["Полная защита автомобиля","220 000"],["Передняя часть автомобиля","95 000"],["Капот","25 000"],["Передний бампер","30 000"],["Фары","12 000"]],
"Хромзона":[["Полный антихром","45 000"],["Оконные молдинги","18 000"],["Решётка радиатора","15 000"],["Рейлинги","14 000"]]
} as const;
type Category=keyof typeof data;
export function Pricing(){const [category,setCategory]=useState<Category>("Виниловая плёнка");const sectionRef=useRef<HTMLElement>(null);useEffect(()=>{const section=sectionRef.current;if(!section||!window.matchMedia("(min-width: 1280px) and (prefers-reduced-motion: no-preference)").matches)return;if(completedScenes.has("pricing")){section.dataset.revealed="true";section.dataset.motion="complete";return;}const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){completedScenes.add("pricing");section.dataset.revealed="true";observer.disconnect();}},{rootMargin:"0px 0px -35% 0px"});observer.observe(section);return()=>observer.disconnect();},[]);return <div className={styles.stage}><section ref={sectionRef} data-revealed="false" id="pricing" className={styles.section} aria-labelledby="pricing-title"><div className={styles.inner}><div className={styles.intro} data-scene-heading><div className={styles.kicker}>СТОИМОСТЬ УСЛУГ<i/></div><h2 id="pricing-title" className={styles.title}>Прайс-<span>лист</span></h2><p className={styles.lead}>Прозрачные и честные цены на все виды работ. Выберите категорию, чтобы посмотреть подробный прайс.</p></div><div className={styles.panel}><div className={styles.tabs}>{(Object.keys(data) as Category[]).map(x=><button key={x} className={category===x?styles.active:styles.tab} onClick={()=>setCategory(x)}>{x}</button>)}</div><div className={styles.desc}><strong>{category.toUpperCase()}</strong><p>{category==="Виниловая плёнка"?"Оклейка кузова и отдельных элементов в любой цвет и фактуру.":category==="Защитная плёнка"?"Защита кузова и отдельных элементов от сколов, царапин и дорожного воздействия.":"Работа с хромированными элементами экстерьера автомобиля."}</p></div><div className={styles.table}><div className={styles.head}><span>Услуга</span><span>Стоимость, ₽</span></div>{data[category].map(([name,price])=><div className={styles.row} key={name}><span>{name}</span><span className={styles.price}><small>от</small><b>{price}</b></span></div>)}</div></div></div></section></div>}